### Get all users
POST http://localhost:3000/api/users
Content-Type: :application/json

{
  "email":"best@example.com",
  "password":"123mypassword"
}

###

### Add a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "best@example.com",
  "password": "123mypassword"
}


###
POST https://localhost:3000//upload
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="video"; filename="myvideo.mp4"
Content-Type: video/mp4

< ./myvideo.mp4
--boundary--

